<?php

namespace AppBundle\Repository;

/**
 * FlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlatRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findActiveOrdered(){
        return $this->createQueryBuilder("f")
            ->andWhere("f.expiresAt > :now")
            ->setParameter("now", new \DateTime())
            ->orderBy("f.expiresAt", "ASC")
            ->getQuery()
            ->getResult();
    }
}
